title: "Deadlock Pro Guides"
description: "A Enciclopédia Competitiva Definitiva de Deadlock. Domine o High MMR com Análise Cirúrgica."
theme: jekyll-theme-slate

# Boas práticas de SEO nativas do GitHub Pages
google_analytics: "" # Você pode adicionar sua tag do Analytics (G-XXXXX) futuramente aqui
show_downloads: false
